from fastapi import FastAPI
import uvicorn
from routes.image import router as image_router
from config import PORT

app = FastAPI(
    title="AI Image Description API",
    description="Send an image URL to get a description generated by an AI model.",
    version="1.0.0",
)

app.include_router(image_router, prefix="/api")


@app.get("/")
def read_root():
    return {"message": "Welcome to the AI Image Description API"}


if __name__ == "__main__":
    uvicorn.run("main:app", host="0.0.0.0", port=int(PORT), reload=True)
